[project]
name = "ltx-core"
version = "1.0.0"
description = "Core implementation of Lightricks' LTX-2 model"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch~=2.7",
    "torchaudio",
    "einops",
    "numpy",
    "transformers>=4.52",
    "safetensors",
    "accelerate",
    "scipy>=1.14",
]

[project.optional-dependencies]
xformers = ["xformers"]
fp8-trtllm = [
    "tensorrt-llm==1.0.0",
    "onnx>=1.16.0,<1.20.0",
    "openmpi",
]

[tool.uv]
conflicts = [
  [
    { extra = "xformers" },
    { extra = "fp8-trtllm" },
  ],
]

[tool.uv.sources]
xformers = { index = "pytorch" }
tensorrt-llm = { index = "nvidia" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"
explicit = true

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "scikit-image>=0.25.2",
]
